// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbNkDtn0uBjHYKuj3PVytf6nlSPH51kc',
    appId: '1:424805542042:web:ce452dddecf30d52d21723',
    messagingSenderId: '424805542042',
    projectId: 'job-search-app-d5aa7',
    authDomain: 'job-search-app-d5aa7.firebaseapp.com',
    storageBucket: 'job-search-app-d5aa7.appspot.com',
    measurementId: 'G-E0JVSGWDKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-pCzLolWMcp8zSOQ7qEXzKR0ony9bP4M',
    appId: '1:424805542042:android:d4dd78a8ee29c0d2d21723',
    messagingSenderId: '424805542042',
    projectId: 'job-search-app-d5aa7',
    storageBucket: 'job-search-app-d5aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqO7KI-bGz9apTqPIyTBWRwZcGZjJaC0o',
    appId: '1:424805542042:ios:d7ff5c6deb27ddf5d21723',
    messagingSenderId: '424805542042',
    projectId: 'job-search-app-d5aa7',
    storageBucket: 'job-search-app-d5aa7.appspot.com',
    iosBundleId: 'com.jobsearch.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqO7KI-bGz9apTqPIyTBWRwZcGZjJaC0o',
    appId: '1:424805542042:ios:b93bb36b9ad8da2cd21723',
    messagingSenderId: '424805542042',
    projectId: 'job-search-app-d5aa7',
    storageBucket: 'job-search-app-d5aa7.appspot.com',
    iosBundleId: 'com.example.job.RunnerTests',
  );
}
